### ISSUE TITLE
Error while compilation 

### ISSUE THREAD

**Issue by 1N73LL1G3NC3x** [Kudaes/RustChain#1]
Compiling dinvoke v0.1.0 (C:\Users\Administrator\Downloads\RustChain-main\RustChain-main\RustChain\dinvoke)
warning: variable does not need to be mutable
  --> dinvoke\src\lib.rs:33:13
   |
33 |         let mut context: *mut CONTEXT = std::mem::transmute(lp_context);
   |             ----^^^^^^^
   |             |
   |             help: remove this mut
   |
   = note: #[warn(unused_mut)] on by default

error: assigning to &T is undefined behavior, consider using an UnsafeCell
   --> dinvoke\src\lib.rs:291:21
    |
283 |                 let mut fun_name: *mut String = std::mem::transmute(&String::default());
    |                                                 --------------------------------------- casting happend here
...
291 |                     *fun_name = function_name.to_string();
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: for more information, visit <https://doc.rust-lang.org/book/ch15-05-interior-mutability.html>
    = note: #[deny(invalid_reference_casting)] on by default

warning: dinvoke (lib) generated 1 warning
error: could not compile dinvoke (lib) due to previous error; 1 warning emitted
![8A874043-AEFC-4354-A18F-198480A81F92](https://github.com/Kudaes/RustChain/assets/143444649/f2bb3cdf-025d-4b26-b557-4f646682198e)

**Comment by Kudaes** [comment]
Yeah, this is due to the new Rust version 1.73. The last commit should have this issue fixed.
