### ISSUE TITLE
Sleep time

### ISSUE THREAD

**Issue by R3d-T3am** [Kudaes/RustChain#3]
Line 33 in /RustChain/src/lib.rs takes 15000, as sleep duration. If i compile it with "cargo build", it sleeps for 4-5 sec regardless of the argument. If i use "cargo build --release", then sleep duration will be same as arg, but as mentioned in previos issue, memory is RX all the way.

**Comment by Kudaes** [comment]
Hi mate, and sorry for the delay in answering.

I am completely rewriting this tool with a colleague and we will release it very soon, so I recommend you to wait until then to test a complete weaponization and more stable version of this technique.

Thank you!
